/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cyber_warrior.glb 
Author: Orbelin_Jaimes (https://sketchfab.com/orbelin.jaimes)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyber-warrior-86f58bf5151c410facacf0ed6a2ebd53
Title: Cyber_warrior
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Cyber(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/cyber_warrior.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  React.useEffect(() => {
    if (actions) {
      const firstAction = Object.values(actions)[0]
      firstAction?.reset().play()
    }
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="d81bdc7f1b29457495c25b0fab55d451fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="group1">
                  <group name="Object_5">
                    <group name="group">
                      <group name="Cyber_warrior_for_substancepolySurface1" />
                    </group>
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.blinn1} skeleton={nodes.Object_7.skeleton} />
                  </group>
                </group>
                <group name="group_1">
                  <group name="Low">
                    <mesh name="Low_material0_0" geometry={nodes.Low_material0_0.geometry} material={materials.material0} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/cyber_warrior.glb')
